spring.application.name=crm-simples

# Configurações do banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/crm_simples
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Faz o Spring criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect